// Generated by reactions/build-geometry.mjs from PubChem 3D conformer SDF files.
// Do not edit by hand. Units: ångström. bonds: [i, j, order].
export const GEOMETRY = {
 "O2": {
  "name": "Oxygen",
  "source": "PubChem CID 977 3D conformer",
  "atoms": [
   [
    "O",
    -0.616,
    0,
    0
   ],
   [
    "O",
    0.616,
    0,
    0
   ]
  ],
  "bonds": [
   [
    0,
    1,
    2
   ]
  ]
 },
 "H2O": {
  "name": "Water",
  "source": "PubChem CID 962 3D conformer",
  "atoms": [
   [
    "O",
    0,
    0,
    0
   ],
   [
    "H",
    0.2774,
    0.8929,
    0.2544
   ],
   [
    "H",
    0.6068,
    -0.2383,
    -0.7169
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ]
  ]
 },
 "CH4": {
  "name": "Methane",
  "source": "PubChem CID 297 3D conformer",
  "atoms": [
   [
    "C",
    0,
    0,
    0
   ],
   [
    "H",
    0.5541,
    0.7996,
    0.4965
   ],
   [
    "H",
    0.6833,
    -0.8134,
    -0.2536
   ],
   [
    "H",
    -0.7782,
    -0.3735,
    0.6692
   ],
   [
    "H",
    -0.4593,
    0.3874,
    -0.9121
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ],
   [
    0,
    3,
    1
   ],
   [
    0,
    4,
    1
   ]
  ]
 },
 "CO2": {
  "name": "Carbon dioxide",
  "source": "PubChem CID 280 3D conformer",
  "atoms": [
   [
    "O",
    -1.197,
    0,
    0
   ],
   [
    "O",
    1.197,
    0,
    0
   ],
   [
    "C",
    0,
    0,
    0
   ]
  ],
  "bonds": [
   [
    0,
    2,
    2
   ],
   [
    1,
    2,
    2
   ]
  ]
 },
 "H2O2": {
  "name": "Hydrogen peroxide",
  "source": "PubChem CID 784 3D conformer",
  "atoms": [
   [
    "O",
    0.7247,
    0,
    0
   ],
   [
    "O",
    -0.7247,
    0,
    0
   ],
   [
    "H",
    0.8233,
    -0.7,
    -0.6676
   ],
   [
    "H",
    -0.8233,
    -0.6175,
    0.7446
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ],
   [
    1,
    3,
    1
   ]
  ]
 },
 "H2": {
  "name": "Hydrogen",
  "source": "PubChem CID 783 has no 3D conformer; H–H r_e 0.7414 Å from NIST CCCBDB",
  "atoms": [
   [
    "H",
    -0.3707,
    0,
    0
   ],
   [
    "H",
    0.3707,
    0,
    0
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ]
  ]
 }
};
