// Molecule catalog for the gallery. One teaching sentence each. No preparations.

export const CATEGORIES = [
  {
    id: "history",
    name: "History-changers & life-savers",
    blurb: "Molecules that changed medicine, materials, or what a cell can do.",
  },
  {
    id: "wonders",
    name: "Molecular wonders & strange shapes",
    blurb: "A ball, a cube, a prism, a house, a tube. The shape is the lesson.",
  },
  {
    id: "sensory",
    name: "Sensory explosions",
    blurb: "A few atoms in the right pattern, and a nose or a tongue notices.",
  },
  {
    id: "energy",
    name: "High energy & explosives",
    blurb: "Famous because they release energy fast. Names and public facts only.",
  },
  {
    id: "extremes",
    name: "Chemical extremes",
    blurb: "Molecules at the edge of what a body or a container can stand.",
  },
  {
    id: "mind",
    name: "Mind-alterers & neurotransmitters",
    blurb: "Signals between nerve cells, and molecules that change those signals.",
  },
  {
    id: "materials",
    name: "Materials & technological marvels",
    blurb: "The piece that a fiber, a plastic, or a crystal repeats.",
  },
  {
    id: "cosmos",
    name: "Cosmos & atmosphere",
    blurb: "Small molecules in air, clouds, rocks, and the space between stars.",
  },
  {
    id: "bio",
    name: "Botanical & animal anomalies",
    blurb: "Made by a plant or an animal, and strange enough to study on purpose.",
  },
  {
    id: "future",
    name: "Future & exotic",
    blurb: "Predicted, glimpsed, or still a sketch. Labeled that way.",
  },
];

export const MOLECULES = [
  // History-changers & life-savers
  { id: "urea", name: "Urea", formula: "CH4N2O", category: "history", structureMode: "ballstick", teach: "Urea is the nitrogen waste in urine. Making it from inorganic salts showed that an organic molecule did not need a living body." },
  { id: "benzene", name: "Benzene", formula: "C6H6", category: "history", structureMode: "ballstick", teach: "Benzene is a ring of six carbons and six hydrogens. That ring shows up in dyes, fuels, and many medicines.", note: "All six carbon–carbon bonds in this model are the same length, 1.395 Å." },
  { id: "penicillin-g", name: "Penicillin G", formula: "C16H18N2O4S", category: "history", structureMode: "ballstick", teach: "Penicillin G is an antibiotic. Its use opened the antibiotic age.", note: "This is the natural shape." },
  { id: "aspirin", name: "Acetylsalicylic acid", formula: "C9H8O4", category: "history", structureMode: "ballstick", teach: "Aspirin is a pain reliever and a fever reducer. This drawing is acetylsalicylic acid." },
  { id: "paracetamol", name: "Paracetamol", formula: "C8H9NO2", category: "history", structureMode: "ballstick", teach: "Paracetamol, also called acetaminophen, is a common pain reliever and fever reducer." },
  { id: "ibuprofen", name: "Ibuprofen", formula: "C13H18O2", category: "history", structureMode: "ballstick", teach: "Ibuprofen is a pain reliever. This model is the S form, the mirror image that does the work. Many tablets contain both mirror images." },
  { id: "dna", name: "DNA", formula: "", formulaLabel: "double helix", category: "history", structureMode: "card-only", teach: "DNA is the double helix that stores genetic instructions, a polymer of four bases, too long for one model here." },
  { id: "glucose", name: "Glucose", formula: "C6H12O6", category: "history", structureMode: "ballstick", teach: "Glucose is the sugar your cells use for fuel. This model is β-D-glucose in the chair shape." },
  { id: "sucrose", name: "Sucrose", formula: "C12H22O11", category: "history", structureMode: "ballstick", teach: "Sucrose is table sugar. One half is glucose and the other half is fructose.", note: "The six-membered ring is the glucose half. The five-membered ring is the fructose half." },
  { id: "quinine", name: "Quinine", formula: "C20H24N2O2", category: "history", structureMode: "ballstick", teach: "Quinine is a malaria medicine first taken from cinchona bark.", note: "This is quinine, not quinidine." },
  { id: "morphine", name: "Morphine", formula: "C17H19NO3", category: "history", structureMode: "card-only", teach: "Morphine is a powerful pain medicine from the opium poppy. It is tightly controlled." },
  { id: "insulin", name: "Insulin", formula: "", formulaLabel: "protein", category: "history", structureMode: "card-only", teach: "Insulin is a protein hormone. People with type 1 diabetes take a medical form of it." },
  { id: "ethinylestradiol", name: "Ethinylestradiol", formula: "C20H24O2", category: "history", structureMode: "ballstick", teach: "Ethinylestradiol is a synthetic estrogen used in many birth-control pills.", note: "The ethynyl and the OH on the same carbon point opposite ways, the form used in the medicine." },
  { id: "teflon", name: "Polytetrafluoroethylene", formula: "", formulaLabel: "(C2F4)n", category: "history", structureMode: "card-only", teach: "Teflon is polytetrafluoroethylene, a slippery plastic of repeating CF2 units." },
  { id: "paclitaxel", name: "Paclitaxel", formula: "C47H51NO14", category: "history", structureMode: "card-only", teach: "Paclitaxel, also called taxol, is a chemotherapy medicine first found in yew bark." },

  // Molecular wonders & strange shapes
  { id: "buckminsterfullerene", name: "Buckminsterfullerene", formula: "C60", category: "wonders", structureMode: "ballstick", teach: "Buckminsterfullerene is sixty carbons in a soccer-ball cage: twelve pentagons and twenty hexagons.", note: "Shorter bonds sit between two hexagons (1.391 Å). Longer bonds sit on the pentagons (1.455 Å)." },
  { id: "cubane", name: "Cubane", formula: "C8H8", category: "wonders", structureMode: "ballstick", teach: "Cubane is eight CH units on the corners of a cube, so the carbon angles are 90° instead of tetrahedral." },
  { id: "prismane", name: "Prismane", formula: "C6H6", category: "wonders", structureMode: "ballstick", teach: "Prismane is a triangular prism of six CH units, a strained isomer of benzene." },
  { id: "olympiadane", name: "Olympiadane", formula: "C216H228F72N12O30P12", category: "wonders", structureMode: "card-only", teach: "Olympiadane is five molecular rings interlocked in a chain, named for the Olympic rings." },
  { id: "nanokid", name: "NanoKid", formula: "C39H42O2", category: "wonders", structureMode: "card-only", teach: "NanoKid is a real molecule drawn to look like a person, with oxygen atoms for the eyes." },
  { id: "bullvalene", name: "Bullvalene", formula: "C10H10", category: "wonders", structureMode: "card-only", teach: "Bullvalene, C10H10, keeps rearranging at room temperature so the carbons trade places." },
  { id: "fenestrane", name: "Fenestrane", formula: "C9H12", category: "wonders", structureMode: "card-only", teach: "The windowpane molecule here is [4.4.4.4]fenestrane, C9H12, a flattened carbon center with four fused rings." },
  { id: "pagodane", name: "Pagodane", formula: "C20H20", category: "wonders", structureMode: "card-only", teach: "Pagodane is a cage hydrocarbon, C20H20, named because the shape stacks like a pagoda." },
  { id: "housane", name: "Housane", formula: "C5H8", category: "wonders", structureMode: "ballstick", teach: "Housane is bicyclo[2.1.0]pentane. The shape is a square of carbons with a triangular roof." },
  { id: "nanotube", name: "Carbon nanotube", formula: "C40H20", category: "wonders", structureMode: "ballstick", teach: "This is a short (5,5) nanotube: forty carbons in hexagons, rolled, with hydrogen on the open ends.", note: "Each carbon–carbon link is the graphite length, about 1.42 Å. The straight-line distance in this rolled model is 1.41–1.42 Å." },

  // Sensory explosions
  { id: "capsaicin", name: "Capsaicin", formula: "C18H27NO3", category: "sensory", structureMode: "ballstick", teach: "Capsaicin is the molecule that makes a chili feel hot. It trips a heat sensor; it is not a flame.", note: "The chain has a trans double bond." },
  { id: "miraculin", name: "Miraculin", formula: "", formulaLabel: "protein", category: "sensory", structureMode: "card-only", teach: "Miraculin is a protein in miracle fruit that makes sour foods taste sweet for a while." },
  { id: "thaumatin", name: "Thaumatin", formula: "", formulaLabel: "protein", category: "sensory", structureMode: "card-only", teach: "Thaumatin is a very sweet protein from a West African fruit." },
  { id: "geosmin", name: "Geosmin", formula: "C12H22O", category: "sensory", structureMode: "ballstick", teach: "Geosmin is the molecule that makes rain on dry soil smell the way it does.", note: "This is the form soil bacteria make." },
  { id: "thioacetone", name: "Thioacetone", formula: "C3H6S", category: "sensory", structureMode: "ballstick", teach: "Thioacetone is famous for a smell so strong that a little of it empties a room." },
  { id: "vanillin", name: "Vanillin", formula: "C8H8O3", category: "sensory", structureMode: "ballstick", teach: "Vanillin is the main molecule in the smell of vanilla." },
  { id: "menthol", name: "Menthol", formula: "C10H20O", category: "sensory", structureMode: "ballstick", teach: "Menthol is the cooling molecule in mint. This model is (−)-menthol in the chair shape." },
  { id: "trimethylamine", name: "Trimethylamine", formula: "C3H9N", category: "sensory", structureMode: "ballstick", teach: "Trimethylamine smells like old fish. Bodies make a little of it, and bacteria make more.", note: "Nitrogen sits at the top of a shallow pyramid. Each carbon–nitrogen–carbon angle in this model is 110.5°." },
  { id: "cadaverine", name: "Cadaverine", formula: "C5H14N2", category: "sensory", structureMode: "ballstick", teach: "Cadaverine is one of the molecules in the smell of decay. It is a five-carbon diamine." },
  { id: "isoamyl-acetate", name: "Isoamyl acetate", formula: "C7H14O2", category: "sensory", structureMode: "ballstick", teach: "Isoamyl acetate smells like banana. It is the ester in some candies and in a ripe banana." },
  { id: "acetic-acid", name: "Acetic acid", formula: "C2H4O2", category: "sensory", structureMode: "ballstick", teach: "Acetic acid is the sour molecule in vinegar." },
  { id: "citric-acid", name: "Citric acid", formula: "C6H8O7", category: "sensory", structureMode: "ballstick", teach: "Citric acid is the sour molecule in lemons. Cells also use it while they break food down for energy." },
  { id: "limonene", name: "(R)-Limonene", formula: "C10H16", category: "sensory", structureMode: "ballstick", teach: "This is (R)-limonene, the form in orange peel. Its mirror image smells more like pine or lemon." },
  { id: "carvone-r", name: "(R)-Carvone", formula: "C10H14O", category: "sensory", structureMode: "ballstick", teach: "This is (R)-carvone. It smells like spearmint. Its mirror image, (S)-carvone, smells like caraway." },
  { id: "carvone-s", name: "(S)-Carvone", formula: "C10H14O", category: "sensory", structureMode: "ballstick", teach: "This is (S)-carvone. It smells like caraway. It is the mirror image of the spearmint form." },

  // High energy & explosives — cards only
  { id: "tnt", name: "TNT", formula: "C7H5N3O6", category: "energy", structureMode: "card-only", restraint: true, teach: "TNT is a solid explosive that shows up in lessons about demolition and war." },
  { id: "nitroglycerin", name: "Nitroglycerin", formula: "C3H5N3O9", category: "energy", structureMode: "card-only", restraint: true, teach: "Nitroglycerin is both an old heart medicine and a powerful explosive." },
  { id: "azidoazide", name: "Azidoazide azide", formula: "C2N14", category: "energy", structureMode: "card-only", restraint: true, teach: "Azidoazide azide is a nitrogen-rich molecule, formula C2N14, so sensitive that shock can set it off." },
  { id: "octanitrocubane", name: "Octanitrocubane", formula: "C8N8O16", category: "energy", structureMode: "card-only", restraint: true, teach: "Octanitrocubane is cubane with a nitro group on every carbon, studied as a high-energy material." },
  { id: "hmx", name: "HMX", formula: "C4H8N8O8", category: "energy", structureMode: "card-only", restraint: true, teach: "HMX, also called octogen, is a powerful explosive used in military charges." },
  { id: "cl-20", name: "CL-20", formula: "C6H6N12O12", category: "energy", structureMode: "card-only", restraint: true, teach: "CL-20 is a modern high-energy explosive studied for propellants and charges." },
  { id: "ammonium-nitrate", name: "Ammonium nitrate", formula: "N2H4O3", formulaLabel: "NH4NO3", category: "energy", structureMode: "card-only", restraint: true, teach: "Ammonium nitrate is a fertilizer salt that can explode if it is stored or heated wrongly." },
  { id: "tatp", name: "Acetone peroxide", formula: "C9H18O6", category: "energy", structureMode: "card-only", restraint: true, teach: "TATP is an unstable explosive that has been used in attacks. Making it is a crime." },
  { id: "clf3", name: "Chlorine trifluoride", formula: "ClF3", category: "energy", structureMode: "card-only", restraint: true, teach: "Chlorine trifluoride can set fire to materials that do not usually burn." },
  { id: "foof", name: "Dioxygen difluoride", formula: "O2F2", category: "energy", structureMode: "card-only", restraint: true, teach: "Dioxygen difluoride, FOOF, reacts violently with most things it touches, even when very cold." },

  // Chemical extremes — cards only
  { id: "botulinum", name: "Botulinum toxin", formula: "", formulaLabel: "protein", category: "extremes", structureMode: "card-only", restraint: true, teach: "Botulinum toxin is a protein from a bacterium, among the most poisonous substances known. A medical form is used in tiny controlled doses." },
  { id: "fluoroantimonic-acid", name: "Fluoroantimonic acid", formula: "HSbF6", category: "extremes", structureMode: "card-only", restraint: true, teach: "Fluoroantimonic acid is among the strongest acids known." },
  { id: "vx", name: "VX", formula: "C11H26NO2PS", category: "extremes", structureMode: "card-only", restraint: true, teach: "VX is a nerve agent, illegal to make or keep. It stops nerves from turning a signal off." },
  { id: "maitotoxin", name: "Maitotoxin", formula: "C164H256Na2O68S2", formulaLabel: "C164H256O68S2Na2", category: "extremes", structureMode: "card-only", restraint: true, teach: "Maitotoxin is a huge toxin made by some algae and concentrated in certain fish." },
  { id: "batrachotoxin", name: "Batrachotoxin", formula: "C31H42N2O6", category: "extremes", structureMode: "card-only", restraint: true, teach: "Batrachotoxin is a poison from some frogs and beetles. It holds nerve channels open." },
  { id: "fluoxetine", name: "Fluoxetine", formula: "C17H18F3NO", category: "extremes", structureMode: "card-only", teach: "Fluoxetine, sold as Prozac, is a medicine that changes serotonin signaling." },
  { id: "carbon-monoxide", name: "Carbon monoxide", formula: "CO", category: "extremes", structureMode: "card-only", teach: "Carbon monoxide is a colorless gas. It binds to hemoglobin more tightly than oxygen does." },
  { id: "dimethylmercury", name: "Dimethylmercury", formula: "C2H6Hg", category: "extremes", structureMode: "card-only", restraint: true, teach: "Dimethylmercury is a liquid mercury compound that passes through skin and is extremely poisonous." },
  { id: "cyanide", name: "Hydrogen cyanide", formula: "CHN", formulaLabel: "HCN", category: "extremes", structureMode: "card-only", restraint: true, teach: "Hydrogen cyanide is a fast poison. It blocks cells from using oxygen." },
  { id: "polonium-hexafluoride", name: "Polonium hexafluoride", formula: "F6Po", formulaLabel: "PoF6", category: "extremes", structureMode: "card-only", restraint: true, teach: "Polonium hexafluoride is written PoF6. Polonium is radioactive, and this is not a classroom chemical." },

  // Mind-alterers & neurotransmitters
  { id: "dopamine", name: "Dopamine", formula: "C8H11NO2", category: "mind", structureMode: "ballstick", teach: "Dopamine is a neurotransmitter tied to reward, movement, and attention.", note: "This model is the neutral molecule. In the body the nitrogen is usually charged." },
  { id: "adrenaline", name: "Adrenaline", formula: "C9H13NO3", category: "mind", structureMode: "ballstick", teach: "Adrenaline, also called epinephrine, is the hormone of a sudden scare. This is the R form the body makes.", note: "This model is the neutral molecule. In the body the nitrogen is usually charged." },
  { id: "l-dopa", name: "L-DOPA", formula: "C9H11NO4", category: "mind", structureMode: "ballstick", teach: "L-DOPA is the amino acid the body turns into dopamine. This is the L form used as a medicine.", note: "This model is the neutral acid. In water the nitrogen is usually charged." },
  { id: "histamine", name: "Histamine", formula: "C5H9N3", category: "mind", structureMode: "ballstick", teach: "Histamine is the signal behind a hive, a sneeze, and a lot of stomach acid.", note: "This model is the neutral molecule. In the body the side-chain nitrogen is usually charged." },
  { id: "serotonin", name: "Serotonin", formula: "C10H12N2O", category: "mind", structureMode: "ballstick", teach: "Serotonin is a neurotransmitter that lessons connect with mood, sleep, and digestion.", note: "This model is the neutral molecule. In the body the side-chain nitrogen is usually charged." },
  { id: "caffeine", name: "Caffeine", formula: "C8H10N4O2", category: "mind", structureMode: "ballstick", teach: "Caffeine is the molecule in coffee and tea that keeps you alert.", note: "The rings are aromatic." },
  { id: "lsd", name: "LSD", formula: "C20H25N3O", category: "mind", structureMode: "card-only", restraint: true, teach: "LSD is a synthetic molecule that changes perception. Possessing it without authority is illegal." },
  { id: "psilocybin", name: "Psilocybin", formula: "C12H17N2O4P", category: "mind", structureMode: "card-only", restraint: true, teach: "Psilocybin is the molecule in some mushrooms that changes perception." },
  { id: "thc", name: "THC", formula: "C21H30O2", category: "mind", structureMode: "card-only", restraint: true, teach: "THC is the main molecule in cannabis that changes mood and perception." },
  { id: "nicotine", name: "Nicotine", formula: "C10H14N2", category: "mind", structureMode: "card-only", teach: "Nicotine is the addictive molecule in tobacco. It acts on nerve receptors." },
  { id: "oxytocin", name: "Oxytocin", formula: "C43H66N12O12S2", category: "mind", structureMode: "card-only", teach: "Oxytocin is a small peptide hormone tied to birth, bonding, and milk release." },
  { id: "endorphins", name: "Endorphins", formula: "", formulaLabel: "peptides", category: "mind", structureMode: "card-only", teach: "Endorphins are a family of peptides the body uses to dull pain." },
  { id: "gaba", name: "GABA", formula: "C4H9NO2", category: "mind", structureMode: "ballstick", teach: "GABA is the main calming neurotransmitter in the brain. The name is gamma-aminobutyric acid.", note: "This model is the neutral acid. In water the nitrogen is usually charged and the acid has given up its hydrogen." },

  // Materials
  { id: "graphene", name: "Graphene", formula: "", formulaLabel: "carbon sheet", category: "materials", structureMode: "card-only", teach: "Graphene is a sheet of carbon hexagons, one atom thick. It is not one small molecule." },
  { id: "kevlar", name: "Kevlar", formula: "", formulaLabel: "(C14H10N2O2)n", category: "materials", structureMode: "card-only", teach: "Kevlar is a strong fiber. The repeat is two benzene rings joined by amide links." },
  { id: "nylon-66", name: "Nylon 6,6", formula: "", formulaLabel: "(C12H22N2O2)n", category: "materials", structureMode: "card-only", teach: "Nylon 6,6 is a fiber. Each repeat has two stretches of six carbons and amide links." },
  { id: "spidroin", name: "Spider silk", formula: "", formulaLabel: "protein", category: "materials", structureMode: "card-only", teach: "Spider silk is a protein fiber. The strength is in how the chains pack." },
  { id: "mbba", name: "MBBA", formula: "C18H21NO", category: "materials", structureMode: "ballstick", teach: "MBBA is a liquid crystal: a rod-shaped molecule that lines up and still flows.", note: "The carbon–nitrogen double bond is trans, which makes the rod." },
  { id: "barium-titanate", name: "Barium titanate", formula: "BaO3Ti", formulaLabel: "BaTiO3", category: "materials", structureMode: "card-only", teach: "Barium titanate, BaTiO3, is a ceramic that stores electric charge." },
  { id: "perovskite", name: "Perovskite", formula: "", formulaLabel: "CH3NH3PbX3", category: "materials", structureMode: "card-only", teach: "This perovskite is a solar-cell crystal: a methylammonium ion, lead, and a halide (the X)." },
  { id: "chitin", name: "Chitin", formula: "", formulaLabel: "(C8H13NO5)n", category: "materials", structureMode: "card-only", teach: "Chitin is the tough repeat in insect shells and in many mushroom walls." },
  { id: "polyethylene", name: "Polyethylene", formula: "", formulaLabel: "(C2H4)n", category: "materials", structureMode: "card-only", teach: "Polyethylene is the plastic in many bags and bottles. The chain repeats as CH2 units." },
  { id: "pdms", name: "Silicone", formula: "", formulaLabel: "(C2H6OSi)n", category: "materials", structureMode: "card-only", teach: "This silicone is PDMS, a flexible chain of silicon–oxygen links with methyl groups." },

  // Cosmos & atmosphere
  { id: "water", name: "Water", formula: "H2O", category: "cosmos", structureMode: "ballstick", teach: "Water is bent, not straight. The angle at oxygen in this model is 104.5°." },
  { id: "carbon-dioxide", name: "Carbon dioxide", formula: "CO2", category: "cosmos", structureMode: "ballstick", teach: "Carbon dioxide is a straight line: oxygen, carbon, oxygen. Each carbon–oxygen link is a double bond." },
  { id: "ozone", name: "Ozone", formula: "O3", category: "cosmos", structureMode: "ballstick", teach: "Ozone is three oxygens in a bent chain. It smells sharp near lightning and, high up, blocks ultraviolet light.", note: "Both bonds are 1.278 Å. A book sometimes draws one single and one double; that is one picture of the same two bonds." },
  { id: "methane", name: "Methane", formula: "CH4", category: "cosmos", structureMode: "ballstick", teach: "Methane is the main gas in natural gas. Carbon sits in the middle of four hydrogens, a tetrahedron." },
  { id: "ammonia", name: "Ammonia", formula: "H3N", formulaLabel: "NH3", category: "cosmos", structureMode: "ballstick", teach: "Ammonia is a pyramid: nitrogen and three hydrogens. The angle in this model is 106.7°." },
  { id: "silica", name: "Silica", formula: "O2Si", formulaLabel: "SiO2", category: "cosmos", structureMode: "card-only", teach: "Silica is the silicon–oxygen network in sand and quartz. SiO2 is a ratio, not a small gas molecule." },
  { id: "trihydrogen-cation", name: "Trihydrogen cation", formula: "", formulaLabel: "H3+", category: "cosmos", structureMode: "card-only", teach: "H3+ is a triangle of three hydrogens missing one electron. It is common in space." },
  { id: "endohedral-fullerene", name: "Endohedral fullerenes", formula: "", formulaLabel: "M@C2n", category: "cosmos", structureMode: "card-only", teach: "An endohedral fullerene is a carbon cage with an atom trapped inside, written like La@C82." },
  { id: "sulfuric-acid", name: "Sulfuric acid", formula: "H2O4S", formulaLabel: "H2SO4", category: "cosmos", structureMode: "card-only", teach: "Sulfuric acid is the strong acid of school labs and of a great deal of industry." },
  { id: "iron-oxide", name: "Iron(III) oxide", formula: "Fe2O3", category: "cosmos", structureMode: "card-only", teach: "Iron(III) oxide is the red of rust. Fe2O3 counts two irons for every three oxygens." },

  // Botanical & animal anomalies
  { id: "glycine", name: "Glycine", formula: "C2H5NO2", category: "bio", structureMode: "ballstick", teach: "Glycine is the smallest amino acid. Its central carbon holds two hydrogens, so it has no mirror image.", note: "This model is the neutral acid. In water the nitrogen is usually charged and the acid has given up its hydrogen." },
  { id: "thymine", name: "Thymine", formula: "C5H6N2O2", category: "bio", structureMode: "ballstick", teach: "Thymine is a DNA base. It pairs with adenine. RNA uses uracil in thymine's place." },
  { id: "chlorophyll-a", name: "Chlorophyll a", formula: "C55H72MgN4O5", category: "bio", structureMode: "card-only", teach: "Chlorophyll a is the green pigment that catches light in plants. Magnesium sits in a large ring." },
  { id: "hemoglobin", name: "Hemoglobin", formula: "", formulaLabel: "protein", category: "bio", structureMode: "card-only", teach: "Hemoglobin is the protein in red blood cells that carries oxygen. Iron sits in each heme." },
  { id: "resveratrol", name: "Resveratrol", formula: "C14H12O3", category: "bio", structureMode: "ballstick", teach: "Resveratrol is a molecule in grape skins, studied for what it does in the body.", note: "The link between the rings is trans." },
  { id: "curcumin", name: "Curcumin", formula: "C21H20O6", category: "bio", structureMode: "ballstick", teach: "Curcumin is the yellow molecule in turmeric.", note: "Both links in the chain are trans. This drawing is the diketone." },
  { id: "luciferin", name: "Luciferin", formula: "C11H8N2O3S2", category: "bio", structureMode: "ballstick", teach: "Firefly luciferin is the molecule a firefly uses when it makes light.", note: "This is D-luciferin, the form a firefly uses." },
  { id: "tetrodotoxin", name: "Tetrodotoxin", formula: "C11H17N3O8", category: "bio", structureMode: "card-only", restraint: true, teach: "Tetrodotoxin is the poison in pufferfish. It blocks channels that nerves need to fire." },
  { id: "cantharidin", name: "Cantharidin", formula: "C10H12O4", category: "bio", structureMode: "card-only", restraint: true, teach: "Cantharidin is a blistering molecule made by blister beetles." },
  { id: "charybdotoxin", name: "Charybdotoxin", formula: "", formulaLabel: "peptide", category: "bio", structureMode: "card-only", restraint: true, teach: "Charybdotoxin is a peptide in scorpion venom that blocks a potassium channel." },
  { id: "salvinorin-a", name: "Salvinorin A", formula: "C23H28O8", category: "bio", structureMode: "card-only", restraint: true, teach: "Salvinorin A is the main molecule in the plant Salvia divinorum." },
  { id: "digoxin", name: "Digoxin", formula: "C41H64O14", category: "bio", structureMode: "card-only", restraint: true, teach: "Digoxin is a heart medicine from foxglove. The useful amount and a poisonous amount are different, and the amount is not on this page." },

  // Future & exotic
  { id: "prithivi", name: "Prithivi", formula: "", formulaLabel: "proposed", category: "future", structureMode: "schematic", teach: "Prithivi is listed here as a theoretical name, not a chemical in a bottle. This page does not draw bonds for it." },
  { id: "rotaxanes", name: "Rotaxanes", formula: "", formulaLabel: "interlocked rings", category: "future", structureMode: "card-only", teach: "A rotaxane is a ring trapped on a dumbbell-shaped molecule. It cannot slip off unless a bond breaks." },
  { id: "dna-origami", name: "DNA origami", formula: "", formulaLabel: "folded DNA", category: "future", structureMode: "card-only", teach: "DNA origami folds a long DNA strand into a designed shape, using short strands as staples." },
  { id: "graphyne", name: "Graphyne", formula: "", formulaLabel: "carbon sheet", category: "future", structureMode: "schematic", teach: "Graphyne is a predicted carbon sheet that would mix hexagons with triple-bond links. This card is a label, not a build." },
  { id: "metallic-hydrogen", name: "Metallic hydrogen", formula: "", formulaLabel: "metallic H", category: "future", structureMode: "schematic", teach: "Metallic hydrogen is a form hydrogen may take under extreme pressure, as inside giant planets. It is not mixed in a beaker." },
  { id: "carbyne", name: "Carbyne", formula: "", formulaLabel: "carbon chain", category: "future", structureMode: "schematic", teach: "Carbyne is a predicted chain of carbon with alternating single and triple bonds. Treat it as a sketch." },
  { id: "borromean-rings", name: "Borromean rings", formula: "", formulaLabel: "three rings", category: "future", structureMode: "card-only", teach: "Stoddart’s Borromean rings are three molecular rings linked so that opening one frees the other two." },
  { id: "plutonium-hexafluoride", name: "Plutonium hexafluoride", formula: "F6Pu", formulaLabel: "PuF6", category: "future", structureMode: "card-only", restraint: true, teach: "Plutonium hexafluoride is a radioactive compound written PuF6." },
  { id: "helium-hydride", name: "Helium hydride ion", formula: "", formulaLabel: "HeH+", category: "future", structureMode: "card-only", teach: "HeH+ is a real ion of helium and hydrogen, found in space and tied to the early universe in these lessons." },
  { id: "n8", name: "N8", formula: "N8", category: "future", structureMode: "schematic", restraint: true, teach: "N8 is a predicted molecule made only of nitrogen. It is not a stable bottle on a shelf, and this page does not show how to build it." },
];
