// Generated by acids/build-geometry.mjs from PubChem 3D conformer SDF files.
// Do not edit by hand. Units: ångström. bonds: [i, j, order].
export const GEOMETRY = {
 "HCl": {
  "name": "Hydrogen chloride",
  "source": "PubChem CID 313 3D conformer",
  "atoms": [
   [
    "Cl",
    0,
    0,
    0
   ],
   [
    "H",
    0.6058,
    -0.2053,
    -1.1384
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ]
  ]
 },
 "H2O": {
  "name": "Water",
  "source": "PubChem CID 962 3D conformer",
  "atoms": [
   [
    "O",
    0,
    0,
    0
   ],
   [
    "H",
    0.2774,
    0.8929,
    0.2544
   ],
   [
    "H",
    0.6068,
    -0.2383,
    -0.7169
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ]
  ]
 },
 "H3O": {
  "name": "Hydronium",
  "source": "PubChem CID 123332 3D conformer",
  "atoms": [
   [
    "O",
    0,
    0,
    0
   ],
   [
    "H",
    -0.8619,
    -0.3262,
    0.3643
   ],
   [
    "H",
    -0.1274,
    0.8014,
    -0.5688
   ],
   [
    "H",
    0.4819,
    -0.7164,
    -0.4864
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ],
   [
    0,
    3,
    1
   ]
  ]
 },
 "OH": {
  "name": "Hydroxide",
  "source": "PubChem CID 961 3D conformer",
  "atoms": [
   [
    "O",
    0,
    0,
    0
   ],
   [
    "H",
    0.45,
    -0.1525,
    -0.8454
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ]
  ]
 },
 "CH3COOH": {
  "name": "Acetic acid",
  "source": "PubChem CID 176 3D conformer",
  "atoms": [
   [
    "O",
    -0.3035,
    1.289,
    -0.0002
   ],
   [
    "O",
    -0.98,
    -0.8878,
    -0.0002
   ],
   [
    "C",
    1.3743,
    -0.3516,
    -0.0002
   ],
   [
    "C",
    -0.0907,
    -0.0496,
    0.0006
   ],
   [
    "H",
    1.8368,
    0.057,
    -0.9021
   ],
   [
    "H",
    1.84,
    0.0676,
    0.8952
   ],
   [
    "H",
    1.5207,
    -1.4356,
    0.0064
   ],
   [
    "H",
    -1.2598,
    1.5081,
    -0.0008
   ]
  ],
  "bonds": [
   [
    0,
    3,
    1
   ],
   [
    0,
    7,
    1
   ],
   [
    1,
    3,
    2
   ],
   [
    2,
    3,
    1
   ],
   [
    2,
    4,
    1
   ],
   [
    2,
    5,
    1
   ],
   [
    2,
    6,
    1
   ]
  ]
 }
};
