// Generated by shape/build-geometry.mjs from PubChem 3D conformer SDF files.
// Do not edit by hand. Units: ångström. bonds: [i, j, order].
export const GEOMETRY = {
 "CO2": {
  "name": "Carbon dioxide",
  "source": "PubChem CID 280 3D conformer",
  "atoms": [
   [
    "O",
    -1.197,
    0,
    0
   ],
   [
    "O",
    1.197,
    0,
    0
   ],
   [
    "C",
    0,
    0,
    0
   ]
  ],
  "bonds": [
   [
    0,
    2,
    2
   ],
   [
    1,
    2,
    2
   ]
  ]
 },
 "SO3": {
  "name": "Sulfur trioxide",
  "source": "PubChem CID 24682 3D conformer",
  "atoms": [
   [
    "S",
    0,
    0,
    -0.0003
   ],
   [
    "O",
    -0.6552,
    -1.2949,
    0.0001
   ],
   [
    "O",
    -0.7939,
    1.2148,
    0.0001
   ],
   [
    "O",
    1.4491,
    0.0801,
    0.0001
   ]
  ],
  "bonds": [
   [
    0,
    1,
    2
   ],
   [
    0,
    2,
    2
   ],
   [
    0,
    3,
    2
   ]
  ]
 },
 "CH4": {
  "name": "Methane",
  "source": "PubChem CID 297 3D conformer",
  "atoms": [
   [
    "C",
    0,
    0,
    0
   ],
   [
    "H",
    0.5541,
    0.7996,
    0.4965
   ],
   [
    "H",
    0.6833,
    -0.8134,
    -0.2536
   ],
   [
    "H",
    -0.7782,
    -0.3735,
    0.6692
   ],
   [
    "H",
    -0.4593,
    0.3874,
    -0.9121
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ],
   [
    0,
    3,
    1
   ],
   [
    0,
    4,
    1
   ]
  ]
 },
 "NH3": {
  "name": "Ammonia",
  "source": "PubChem CID 222 3D conformer",
  "atoms": [
   [
    "N",
    0,
    0,
    0
   ],
   [
    "H",
    -0.4417,
    0.2906,
    0.8711
   ],
   [
    "H",
    0.7256,
    0.6896,
    -0.1907
   ],
   [
    "H",
    0.4875,
    -0.8701,
    0.2089
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ],
   [
    0,
    3,
    1
   ]
  ]
 },
 "H2O": {
  "name": "Water",
  "source": "PubChem CID 962 3D conformer",
  "atoms": [
   [
    "O",
    0,
    0,
    0
   ],
   [
    "H",
    0.2774,
    0.8929,
    0.2544
   ],
   [
    "H",
    0.6068,
    -0.2383,
    -0.7169
   ]
  ],
  "bonds": [
   [
    0,
    1,
    1
   ],
   [
    0,
    2,
    1
   ]
  ]
 }
};
